### ISSUE TITLE
panic: could not run [db push]: exit status 1

### ISSUE THREAD

**Issue by dotsinspace** [prisma/prisma-client-go#1434]
Don't know why but this go client is throwing error on my Ubuntu server. on some of them it is working fine. even when i tried to debug it is not showing any helpful information.

**Error currently client is throwing.**
```

The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
Error: Generator "go run github.com/steebchen/prisma-client-go" failed:


panic: could not run [db push]: exit status 1

goroutine 1 [running]:
main.main()
	/home/rnl/go/pkg/mod/github.com/steebchen/prisma-client-go@v0.45.0/main.go:38 +0x665
exit status 2
```

Error with Debug
```
rnl@vmi2298266:~/cm_go$ export DEBUG="*"
rnl@vmi2298266:~/cm_go$ goprisma db push
prisma:engines binaries to download query-engine, schema-engine +1407ms
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +37ms
prisma:get-platform Command "uname -m" successfully returned "x86_64
" +35ms
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +0ms
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +5ms
prisma:get-platform The parsed libssl version is: 3.0.x +2ms
prisma:fetch-engine:env Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /home/rnl/.cache/prisma/binaries/cli/6.0.1/5dbef10bdbfb579e07d35cc85fb1518d357cb99e/prisma-query-engine-linux-static-x64 +1ms
prisma:fetch-engine:env Using env var PRISMA_SCHEMA_ENGINE_BINARY for binary schema-engine, which points to /home/rnl/.cache/prisma/binaries/cli/6.0.1/5dbef10bdbfb579e07d35cc85fb1518d357cb99e/prisma-schema-engine-linux-static-x64 +1ms
prisma:getSchema prismaConfig {
  "packagePath": "/home/rnl/cm_go/package.json"
} +1995ms
prisma:getSchema Checking existence of /home/rnl/cm_go/schema.prisma +1ms
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +1ms
prisma:loadEnv project root found at /home/rnl/cm_go/package.json +7ms
prisma:getSchema prismaConfig {
  "packagePath": "/home/rnl/cm_go/package.json"
} +3ms
prisma:tryLoadEnv Environment variables loaded from /home/rnl/cm_go/.env +0ms
prisma:getConfig Using getConfig Wasm +12ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +18ms
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +38ms
prisma:get-platform Command "uname -m" successfully returned "x86_64
" +41ms
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu") +2ms
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3 +3ms
prisma:get-platform The parsed libssl version is: 3.0.x +3ms
prisma:loadEnv project root found at /home/rnl/cm_go/package.json +1ms
prisma:getSchema prismaConfig {
  "packagePath": "/home/rnl/cm_go/package.json"
} +2ms
prisma:tryLoadEnv Environment variables loaded from /home/rnl/cm_go/.env +1ms
Environment variables loaded from .env
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +1ms
Prisma schema loaded from schema.prisma
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +2ms
prisma:getConfig Using getConfig Wasm +1ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +20ms
Datasource "db": PostgreSQL database "cm", schema "public" at "0.0.0.0:5433"
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +38ms
prisma:getConfig Using getConfig Wasm +11ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +32ms
prisma:fetch-engine:env Using env var PRISMA_SCHEMA_ENGINE_BINARY for binary schema-engine, which points to /home/rnl/.cache/prisma/binaries/cli/6.0.1/5dbef10bdbfb579e07d35cc85fb1518d357cb99e/prisma-schema-engine-linux-static-x64 +17ms
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +225ms
prisma:fetch-engine:env Using env var PRISMA_SCHEMA_ENGINE_BINARY for binary schema-engine, which points to /home/rnl/.cache/prisma/binaries/cli/6.0.1/5dbef10bdbfb579e07d35cc85fb1518d357cb99e/prisma-schema-engine-linux-static-x64 +4ms
prisma:schemaEngine:rpc starting Schema engine with binary: /home/rnl/.cache/prisma/binaries/cli/6.0.1/5dbef10bdbfb579e07d35cc85fb1518d357cb99e/prisma-schema-engine-linux-static-x64 +0ms
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +1ms
prisma:getConfig Using getConfig Wasm +2ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +14ms
prisma:schemaEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"schemaPush","params":{"force":false,"schema":{"files":[{"path":"/home/rnl/cm_go/schema.prisma","content":"generator db {\n  provider = env(\"GENERATOR_PROVIDER\")\n  // optionally provide more configuration options\n  output   = env(\"GENERATOR_OUTPUT\")\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_POSTGRES_WRITE_URL\")\n}\n\n//\n// CLUSTER MANAGER\n// \nmodel Cluster {\n  id           String   @id @unique @default(cuid())\n  createdAt    DateTime @default(now()) @db.Timestamp(6)\n  updatedAt    DateTime @default(now()) @updatedAt @db.Timestamp(6)\n  displayName  String   @unique\n  isRunning    Boolean  @default(false)\n  description  String?\n  System__fk__ String?\n  System       System?  @relation(fields: [System__fk__], references: [id])\n}\n\nmodel System {\n  id                  String             @id @unique @default(cuid())\n  createdAt           DateTime           @default(now()) @db.Timestamp(6)\n  updatedAt           DateTime           @default(now()) @updatedAt @db.Timestamp(6)\n  os                  String?\n  version             String?\n  host                String\n  port                Int\n  username            String\n  password            String?\n  privateKey          String?\n  haveAuthMethod      SYSTEM_AUTH_METHOD @default(PASSWORD)\n  pluginPath          String\n  containerPluginPath String\n  Cluster             Cluster[]\n  Container           Container[]\n}\n\nmodel Container {\n  id                String       @id @unique @default(cuid())\n  createdAt         DateTime     @default(now()) @db.Timestamp(6)\n  updatedAt         DateTime     @default(now()) @updatedAt @db.Timestamp(6)\n  image             String\n  tag               String\n  replica           Int?\n  pluginPath        String\n  // vsCodeLink        String\n  port              Int?\n  network           String?\n  Environment__fk__ String?\n  Environment       Environment? @relation(fields: [Environment__fk__], references: [id])\n  System__fk__      String?\n  System            System?      @relation(fields: [System__fk__], references: [id])\n}\n\nmodel Environment {\n  id        String      @id @unique @default(cuid())\n  createdAt DateTime    @default(now()) @db.Timestamp(6)\n  updatedAt DateTime    @default(now()) @updatedAt @db.Timestamp(6)\n  variables Json\n  Container Container[]\n}\n\nmodel ResourceLimits {\n  id        String   @id @unique @default(cuid())\n  createdAt DateTime @default(now()) @db.Timestamp(6)\n  updatedAt DateTime @default(now()) @updatedAt @db.Timestamp(6)\n  cpu       String\n  memory    String\n}\n\nmodel Type {\n  id          String   @id @unique @default(cuid())\n  createdAt   DateTime @default(now()) @db.Timestamp(6)\n  updatedAt   DateTime @default(now()) @updatedAt @db.Timestamp(6)\n  displayName String   @unique\n  description String\n}\n\nenum SYSTEM_AUTH_METHOD {\n  PASSWORD\n  PRIVATE_KEY\n}\n\n//\n// SIP\n// \nmodel Service {\n  id          String        @id @default(cuid())\n  createdAt   DateTime      @default(now())\n  updatedAt   DateTime      @updatedAt\n  displayName String\n  address     String\n  port        Int\n  metadata    Json?\n  HealthCheck HealthCheck[]\n  Tags        Tag[]\n  ServiceLog  ServiceLog[]\n}\n\nmodel Tag {\n  id            String  @id @default(cuid())\n  displayName   String\n  Service__fk__ String\n  Service       Service @relation(fields: [Service__fk__], references: [id])\n}\n\nmodel HealthCheck {\n  id            String    @id @default(cuid())\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n  httpUrl       String?\n  interval      String?\n  timeout       String?\n  lastStatus    String?\n  lastChecked   DateTime?\n  Service__fk__ String    @unique @default(cuid())\n  Service       Service   @relation(fields: [Service__fk__], references: [id])\n}\n\nmodel ServiceLog {\n  id            String   @id @default(cuid())\n  createdAt     DateTime @default(now())\n  updatedAt     DateTime @updatedAt\n  message       String\n  Service__fk__ String\n  service       Service  @relation(fields: [Service__fk__], references: [id])\n}\n"}]}}} +35ms
prisma:schemaEngine:stderr {"timestamp":"2024-12-26T09:28:26.999371617Z","level":"INFO","fields":{"message":"Starting schema engine RPC server","git_hash":"5dbef10bdbfb579e07d35cc85fb1518d357cb99e"},"target":"schema_engine"} +38ms

The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
prisma:getSchema Reading schema from single file /home/rnl/cm_go/schema.prisma +330ms
prisma:getConfig Using getConfig Wasm +10ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +10ms
prisma:getDMMF Using getDmmf Wasm +2ms
prisma:getDMMF Using given datamodel +1ms
prisma:getDMMF dmmf data retrieved without errors in getDmmf Wasm +310ms
prisma:GeneratorProcess child exited with code 1 on signal null +1477ms
Error: GeneratorError: Generator "go run github.com/steebchen/prisma-client-go" failed:


    at ChildProcess.<anonymous> (/snapshot/node_modules/prisma/build/index.js:314:1732)
    at ChildProcess.emit (node:events:537:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
panic: could not run [db push]: exit status 1

goroutine 1 [running]:
main.main()
	/home/rnl/go/pkg/mod/github.com/steebchen/prisma-client-go@v0.45.0/main.go:38 +0x665
exit status 2
```

Initially i throught that it is due to prisma cli version mistmatch but not. every other prisma client ( Js, Python ) both of them working flawlessly.

**Comment by ynden** [comment]
@dotsinspace I suspect this is an issue with the `generator`, since `prisma db push` performs two operations by default:
1. push the schema to the database
2. generates the client code

I believe 1. is successful, but 2 isn't.

Could you try this command instead: `go run github.com/steebchen/prisma-client-go generate --schema /home/rnl/cm_go/schema.prisma`

I also tried on my side with your schema you posted in the debug, I was able to generate the Go client code.

**Comment by dotsinspace** [comment]
Found out the reason. it only supports specific version of Prisma (0.45 something)  + Prisma Client and Cli need to be same. to get it worked.

**Comment by SOUMITRO-SAHA** [comment]
- Tell me how to fix this issue. 
- It doesn't seem to be working for me.
- I'm facing the same issue.

**Comment by SOUMITRO-SAHA** [comment]
Finally, I was able to resolve the issue. However, there is still a problem with the `generate` command (`go run github.com/steebchen/prisma-client-go generate`).

For now, I am using `go generate` to generate the files.  
Reference: [Prisma Go - Set up go generate](https://goprisma.org/docs/reference/deploy/best-practices#set-up-go-generate)

**System Info:**  
- OS: Linux Ubuntu 22.04 LTS

**Comment by dotsinspace** [comment]
@SOUMITRO-SAHA Try upgrading prisma client around 0.45, Make sure cli and prisma client both are of same version.
