### ISSUE TITLE
Error downloading binary on alpine linux

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#153]
Running into an issue when fetching the query engine on `alpine:3.11.6` docker:

```
api_1       | info: 2020/06/09 22:12:13 no query engine defined or found
api_1       | info: 2020/06/09 22:12:13 if you want to pre-fetch the query engine for better startup performance, specify `binaryTargets = ["native"]` in your Schema.prisma file under "generator" and upload the query engine with your application.
api_1       | info: 2020/06/09 22:12:13 fetching the query engine now...
api_1       | info: 2020/06/09 22:12:14 done.
api_1       | panic: ensure: version check failed: fork/exec /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x: no such file or directory
```

If I attach into the container I see the file is there:

```
info: 2020/06/09 23:26:17 no query engine defined or found
info: 2020/06/09 23:26:17 if you want to pre-fetch the query engine for better startup performance, specify `binaryTargets = ["native"]` in your Schema.prisma file under "generator" and upload the query engine with your application.
info: 2020/06/09 23:26:17 fetching the query engine now...
info: 2020/06/09 23:26:18 done.
panic: ensure: version check failed: fork/exec /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x: no such file or directory

goroutine 1 [running]:
github.com/insideiq/api/pkg/db.Init()
	/go/src/github.com/tarrencev/api/pkg/db/db.go:13 +0x1d6
main.init.0()
	/go/src/github.com/tarrencev/api/main.go:20 +0x3e
/ # ls /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/
prisma-query-engine-debian-openssl-1.1.x      prisma-query-engine-debian-openssl-1.1.x.tmp
```

**Comment by tarrencev** [comment]
Seems platform is just not supported.

```
/ # readelf -l /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x|grep "program interpreter"
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
/ # apk add libc6-compat
(1/1) Installing libc6-compat (1.1.24-r2)
OK: 18 MiB in 20 packages
/ # /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x)
Error relocating /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x: __register_atfork: symbol not found
Error relocating /tmp/prisma/binaries/engines/4dbefe724ae6df3621eb660a5d0e0402e34189bf/prisma-query-engine-debian-openssl-1.1.x: __res_init: symbol not found
```

**Comment by steebchen** [comment]
Thanks for the issue, we have binaries for alpine already, I just need to make the go client aware of them.

**Comment by steebchen** [comment]
@tarrencev Can you please update to the latest version using `go get github.com/prisma/prisma-client-go@master` and try again on an alpine platform, and let me know if there are any issues? Thanks!

**Comment by jakubmeysner** [comment]
@steebchen I've recently been trying to set up a Go project using Prisma to use Alpine Linux and while the Prisma CLI successfully downloads (to take advantage of caching I first run `go run github.com/prisma/prisma-client-go version`) when trying to generate the client I get the following error:

```
panic: could not run [version]: fork/exec /root/.cache/prisma/binaries/cli/2.11.0/prisma-cli-linux: no such file or directory

goroutine 1 [running]:
main.main()
        /go/pkg/mod/github.com/prisma/prisma-client-go@v0.2.0/main.go:29 +0x493
exit status 2
```

**Comment by steebchen** [comment]
@jakubmeysner Can you share your docker file, or at least the image you're using? Feel free to create a new issue for this, since this is a different problem.

**Comment by jakubmeysner** [comment]
@steebchen [done](https://github.com/prisma/prisma-client-go/issues/357).
