### ISSUE TITLE
Following Demo throws an error on db push

### ISSUE THREAD

**Issue by SeanningTatum** [prisma/prisma-client-go#460]
Followed the tutorial step by step and it throws this error.

```bash
demo go run github.com/prisma/prisma-client-go db push --preview-feature
panic: could not run [db push --preview-feature]: signal: segmentation fault

goroutine 1 [running]:
main.main()
        /Users/sean/go/pkg/mod/github.com/prisma/prisma-client-go@v0.7.0/main.go:29 +0x49b
exit status 2
```

**Comment by SeanningTatum** [comment]
Not sure if it's related to this #357, but followed the tutorial on my Windows computer and everything worked smoothly, while on my Mac it just hangs and throws this error.

**Comment by steebchen** [comment]
Could you please set `export DEBUG=*` and `export PHOTON_GO_LOG=debug` and run it again? Otherwise I don't have enough information to think about what could have went wrong.

**Comment by SeanningTatum** [comment]
```
debug: 2021/04/26 20:45:45 invoking command [db push --preview-feature]
debug: 2021/04/26 20:45:45 running cli with args [db push --preview-feature]
debug: 2021/04/26 20:45:45 global cache dir: /Users/sean/Library/Caches
debug: 2021/04/26 20:45:45 ensuring CLI prisma-cli-darwin from /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/prisma-cli-darwin to https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-2.18.0-darwin.gz
debug: 2021/04/26 20:45:45 prisma cli is cached
debug: 2021/04/26 20:45:45 checking query-engine...
debug: 2021/04/26 20:45:45 download url https://binaries.prisma.sh/all_commits/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/darwin/query-engine.gz
debug: 2021/04/26 20:45:45 /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/prisma-query-engine-darwin is cached
debug: 2021/04/26 20:45:45 checking migration-engine...
debug: 2021/04/26 20:45:45 download url https://binaries.prisma.sh/all_commits/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/darwin/migration-engine.gz
debug: 2021/04/26 20:45:45 /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/prisma-migration-engine-darwin is cached
debug: 2021/04/26 20:45:45 checking introspection-engine...
debug: 2021/04/26 20:45:45 download url https://binaries.prisma.sh/all_commits/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/darwin/introspection-engine.gz
debug: 2021/04/26 20:45:45 /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/prisma-introspection-engine-darwin is cached
debug: 2021/04/26 20:45:45 checking prisma-fmt...
debug: 2021/04/26 20:45:45 download url https://binaries.prisma.sh/all_commits/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/darwin/prisma-fmt.gz
debug: 2021/04/26 20:45:45 /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/prisma-prisma-fmt-darwin is cached
debug: 2021/04/26 20:45:45 running /Users/sean/Library/Caches/prisma/binaries/cli/2.18.0/prisma-cli-darwin [db push --preview-feature]
panic: could not run [db push --preview-feature]: signal: segmentation fault

goroutine 1 [running]:
main.main()
        /Users/sean/go/pkg/mod/github.com/prisma/prisma-client-go@v0.7.0/main.go:29 +0x49b
exit status 2
```

**Comment by SeanningTatum** [comment]
Deleting the cache and re-downloading it fixed it for me. Maybe there was a network connection issue while I was downloading the binary.
