### ISSUE TITLE
Quickstart guide shows unusable example

### ISSUE THREAD

**Issue by morawskiOZ** [prisma/prisma-client-go#580]
Seems like quickstart guide, https://github.com/prisma/prisma-client-go/blob/main/docs/quickstart.md does not really work out of the box. The error I got on step 3.:
```
Prisma schema loaded from schema.prisma
Error: Cannot read property 'url' of undefined
```

 I copied everything as it was in the guide. I work on macOs Catalina with go 1.17

 I reckon a lot of ppl will give it a pass since hello world does not really work or it is not explained correctly.

**Comment by steebchen** [comment]
Thanks for reporting this. It works for me on go1.17 (see screenshot below), so it would be great if you could help me debug why it doesn't for you. Can you please send the output of `go run github.com/prisma/prisma-client-go version`? Can you please also set `PHOTON_GO_LOG=true` and `DEBUG=*`, run the command which failed again and send the output here as well? Thank you!

![image](https://user-images.githubusercontent.com/5013932/134019897-2e9899f8-97c5-410b-9ea6-c282ce7c9a4e.png)

**Comment by morawskiOZ** [comment]
thanks for quick response, I set up the envs and here are the results:
```
➜  demo git:(master) ✗ go run github.com/prisma/prisma-client-go version
debug: 2021/09/20 17:44:46 invoking command [version]
debug: 2021/09/20 17:44:46 running cli with args [version]
debug: 2021/09/20 17:44:46 global cache dir: /Users/pmorawski/Library/Caches
debug: 2021/09/20 17:44:46 ensuring CLI prisma-cli-darwin from /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/prisma-cli-darwin to https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-2.26.0-darwin.gz
debug: 2021/09/20 17:44:46 prisma cli is cached
debug: 2021/09/20 17:44:46 checking query-engine...
debug: 2021/09/20 17:44:46 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/query-engine.gz
debug: 2021/09/20 17:44:46 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin is cached
debug: 2021/09/20 17:44:46 checking migration-engine...
debug: 2021/09/20 17:44:46 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/migration-engine.gz
debug: 2021/09/20 17:44:46 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-migration-engine-darwin is cached
debug: 2021/09/20 17:44:46 checking introspection-engine...
debug: 2021/09/20 17:44:46 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/introspection-engine.gz
debug: 2021/09/20 17:44:46 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-introspection-engine-darwin is cached
debug: 2021/09/20 17:44:46 checking prisma-fmt...
debug: 2021/09/20 17:44:46 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/prisma-fmt.gz
debug: 2021/09/20 17:44:46 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-prisma-fmt-darwin is cached
debug: 2021/09/20 17:44:46 running /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/prisma-cli-darwin [version]
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/github/demo/package.json +0ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/github/package.json +1ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/package.json +0ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/package.json +1ms
  prisma:loadEnv skipping package.json at /Users/package.json +0ms
  prisma:loadEnv skipping package.json at /package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin +0ms
  prisma:download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-migration-engine-darwin +0ms
  prisma:download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-introspection-engine-darwin +0ms
  prisma:download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-prisma-fmt-darwin +0ms
  prisma:getConfig Using Query Engine Binary at: /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin +0ms
prisma               : 2.26.0
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-migration-engine-darwin, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-introspection-engine-darwin, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-prisma-fmt-darwin, resolved by PRISMA_FMT_BINARY)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
  prisma:getConfig Using Query Engine Binary at: /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin +15ms
```

```
➜  demo git:(master) ✗ go run github.com/prisma/prisma-client-go db push
debug: 2021/09/20 17:45:43 invoking command [db push]
debug: 2021/09/20 17:45:43 running cli with args [db push]
debug: 2021/09/20 17:45:43 global cache dir: /Users/pmorawski/Library/Caches
debug: 2021/09/20 17:45:43 ensuring CLI prisma-cli-darwin from /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/prisma-cli-darwin to https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-2.26.0-darwin.gz
debug: 2021/09/20 17:45:43 prisma cli is cached
debug: 2021/09/20 17:45:43 checking query-engine...
debug: 2021/09/20 17:45:43 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/query-engine.gz
debug: 2021/09/20 17:45:43 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin is cached
debug: 2021/09/20 17:45:43 checking migration-engine...
debug: 2021/09/20 17:45:43 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/migration-engine.gz
debug: 2021/09/20 17:45:43 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-migration-engine-darwin is cached
debug: 2021/09/20 17:45:43 checking introspection-engine...
debug: 2021/09/20 17:45:43 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/introspection-engine.gz
debug: 2021/09/20 17:45:43 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-introspection-engine-darwin is cached
debug: 2021/09/20 17:45:43 checking prisma-fmt...
debug: 2021/09/20 17:45:43 download url https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/darwin/prisma-fmt.gz
debug: 2021/09/20 17:45:43 /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-prisma-fmt-darwin is cached
debug: 2021/09/20 17:45:43 running /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/prisma-cli-darwin [db push]
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/github/demo/package.json +0ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/github/package.json +1ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/Code/package.json +0ms
  prisma:loadEnv skipping package.json at /Users/pmorawski/package.json +0ms
  prisma:loadEnv skipping package.json at /Users/package.json +0ms
  prisma:loadEnv skipping package.json at /package.json +1ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin +0ms
  prisma:download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-migration-engine-darwin +0ms
  prisma:download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-introspection-engine-darwin +1ms
  prisma:download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-prisma-fmt-darwin +0ms
Prisma schema loaded from schema.prisma
  prisma:getConfig Using Query Engine Binary at: /Users/pmorawski/Library/Caches/prisma/binaries/cli/2.26.0/9b816b3aa13cc270074f172f30d6eda8a8ce867d/prisma-query-engine-darwin +0ms
Error: TypeError: Cannot read property 'url' of undefined
    at Object.getDbInfo (/snapshot/node_modules/prisma/build/index.js:61421:34)
    at async Object.printDatasource (/snapshot/node_modules/prisma/build/index.js:62849:20)
    at async DbPush2.parse (/snapshot/node_modules/prisma/build/index.js:64378:7)
    at async main (/snapshot/node_modules/prisma/build/index.js:110797:18)
panic: could not run [db push]: exit status 1

goroutine 1 [running]:
main.main()
        /Users/pmorawski/go/pkg/mod/github.com/prisma/prisma-client-go@v0.10.0/main.go:29 +0x34c
exit status 2
```

**Comment by steebchen** [comment]
This is really weird... can you also post your prisma.schema please if it differs from the example?
Maybe you could try upgrading to the latest Go client version just to see if it's already fix in the latest version: `go get github.com/prisma/prisma-client-go@main`, and try again. Thanks.

**Comment by morawskiOZ** [comment]
hmm weird after switching to `go get github.com/prisma/prisma-client-go@main` it works fine, and now that I went back to `v.0.10.0` it still works fine, so guess it is my local machine problem and this issue can be closed. Thanks a lot!

**Comment by steebchen** [comment]
Thanks for letting me know! To be fair this part is a bit of a hack as we bundle the node library via pkg and call it from the Go client. I'm glad that it works now. At some point we'll have a better solution via native bindings in place but currently we don't have the capacity to do that.
