### ISSUE TITLE
Panic on connecting: nil pointer

### ISSUE THREAD

**Issue by Bendimester23** [prisma/prisma-client-go#702]
When i try to connect to any database, it panics and stops.
Panic: `

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x60790c]

goroutine 1 [running]:
github.com/prisma/prisma-client-go/runtime/lifecycle.(*Lifecycle).Connect(...)
        /....../go/pkg/mod/github.com/prisma/prisma-client-go@v0.12.2/runtime/lifecycle/lifecycle.go:26
perselus/database.Connect()
        /...../backend/database/connect.go:9 +0x12c
main.main()
        /...../backend/main.go:24 +0x8f
exit status 2`

It is with the latest prisma running on Arch linux.

**Comment by Bendimester23** [comment]
turns out i wrote `newClient` instead of `NewClient`
